baseURL = "https://blog.kien.vc/"
title = "Kien Ventures"
theme = "PaperMod"
languageCode = "en-us"
enableRobotsTXT = true
# Enable sitemap and RSS
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Kien Ventures Blog"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  # SEO and social
  keywords = ["Kien Ventures", "Blog", "Kien.vc"]
  author = "Kien Tran"
  images = ["/images/cover.png"]
  # OpenGraph/Twitter
  env = "production"
  ShowToc = true
  mainSections = ["posts"]
  # Social links (customize as needed)
  socialIcons = [
    { name = "github", url = "https://github.com/kientranasia" },
    { name = "twitter", url = "https://twitter.com/kientranasia" }
  ]
  [params.footer]
    copyright = "© 2025 Kien Ventures"
    text = ""

# Sitemap config
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Enable RSS
[mediaTypes."application/rss+xml"]
  suffixes = ["xml"]

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "index"
  isPlainText = false
  notAlternative = false

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = 1
  [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/kientranasia"
    weight = 2
  [[menu.main]]
    name = "LinkedIn"
    url = "www.linkedin.com/in/kientranasia"
    weight = 3
